# -*- coding: utf-8 -*-
{
    "name": "Colocatere Studio",
    "version": "1.0",
    "summary": "Studio Customisation",
    "description": "Studio Customisation",
    "category": "",
    "author": "Aktiv software",
    "website": "www.aktivsoftware.com",
    "depends": [
        'fleet',
        'col_property',
        'account_anomaly',
        'base_automation',
        'hr',
        'akawam_web_service',
        'account_accountant',
        'account_followup',
        'account',
        'col_payment_import'
    ],
    "data": [
        'security/ir.model.access.csv',
        'data/base_automation.xml',
        'data/ir_actions_server.xml',
        'views/name_views.xml',
        'security/security.xml',
        'views/sale_order_views.xml',
        'views/purchase_order_views.xml',
        'views/property_property_views.xml',
        'views/res_partner_views.xml',
        'views/res_partner_category_view.xml',
        'views/res_company_views.xml',
        'views/account_payment_views.xml',
        'views/product_template_views.xml',
        'views/sdd_mandate_views.xml',
        'views/project_project_views.xml',
        'views/fleet_vehicle_log_contract_views.xml',
        'views/fleet_vehicle_views.xml',
        'views/account_move_views.xml',
        'views/account_move_line_views.xml',
        'views/ir_ui_menu.xml',
        'views/akawam_ws_call_views.xml',
        'views/ir_logging_views.xml',
        'views/maiL_message_views.xml',
        'views/hr_employee_view.xml',
        # 'report/sale_order_report.xml',
        'report/account_move_report.xml',

    ],
    "installable": True,
    "auto_install": False,
    "license": "LGPL-3",
}
